title: Deconvolution for Photodiode Response Maps
description: Exploring the applicability of a microscopy tehcnique to semiconductor characterization
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: G-THNRVSE8J8
