title: Deconvolution Algorithm to Improve Photodiode Response Map
description: Cayman is a clean, responsive theme for GitHub Pages.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-cayman
